security:
    firewalls:
        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Veuillez vous authentifier"

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext