security:
    firewalls:
        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Veuillez vous authentifier"
    providers:
        # mainly for first usage, using parameters.ini file
        in_memory:
            memory:
                users: %users%
        database:
            entity: { class: TrezLogicielTrezBundle:User, property: username }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Trez\LogicielTrezBundle\Entity\User: sha512
    acl:
        connection: default