security:
    firewalls:
        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Veuillez vous authentifier"

    providers:
        database:
            entity: { class: TrezLogicielTrezBundle:User, property: username }

    encoders:
        # for User objects
        Trez\LogicielTrezBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: true