security:
    firewalls:
        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Veuillez vous authentifier"

    providers:
        in_memory:
            memory:
                users: %users%

    encoders:
        # so we can add (dirtyly) users via config file
        # DEPRECATED
        Symfony\Component\Security\Core\User\User: plaintext
        # for User objects
        Trez\LogicielTrezBundle\Entity\User: sha512