security:
    firewalls:
        # first, assets don't need auth
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # first, we have to exclude the (credentials) login page
        login_firewall:
            pattern:    ^/credentials/login$
            anonymous:  ~
        # login using credentials
        classic:
             pattern: ^/credentials
             form_login:
                login_path: /credentials/login
                check_path: /credentials/check
             logout:
                 path: /logout
                 target: /
                 invalidate_session: true
             provider: chain_provider
             context: main_auth  # so users are shared among firewalls
             remember_me:
                key: "%secret%"
                lifetime: 604800 # 1 week in seconds
                path: /
                domain: ~
        # a nice OpenID authentification
        main:
            pattern: ^/
            fp_openid:
                create_user_if_not_exists: true
                provider: openid_user_manager
                required_attributes:
                    - contact/email
                remember_me: false # not sure what it's done?
                login_path: /login
                check_path: /login_check_openid
            logout: true
            anonymous: true
            context: main_auth  # so users are shared among firewalls
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/credentials, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # then, exceptions: pages for all users
        -
            path: ^/$
            roles: ROLE_USER
        -
            path: ^/logout
            roles: ROLE_USER
        -
            path: ^/user/change_password
            roles: ROLE_USER
        -
            path: ^/exercice/$
            roles: ROLE_USER
        -
            path: ^/budget/\d+$
            roles: ROLE_USER
        -
            path: ^/categorie/\d+$
            roles: ROLE_USER
        -
            path: ^/sous_categorie/\d+$
            roles: ROLE_USER
        -
            path: ^/ligne/\d+$
            roles: ROLE_USER
        -
            path: ^/facture/\d+$
            roles: ROLE_USER
        -
            path: ^/facture/detail/\d+/?\d+$
            roles: ROLE_USER
        # the other pages are only for admins
        -
            path: ^/
            roles: ROLE_ADMIN
    providers:
        # provider for OpenID
        openid_user_manager:
            id: trez.logiciel_trez.openid_user_manager
        # the first provider is always used, otherwise specified
        chain_provider:
            chain:
                providers: [in_memory, database]
        in_memory:
            memory:
                users: %users%
        # anyway we have to keep this provider else both auths will not be able to fetch User entities
        database:
            entity: { class: TrezLogicielTrezBundle:User, property: username }
    encoders:
        Trez\LogicielTrezBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_USER: IS_AUTHENTICATED_OPENID