security:
    firewalls:
        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Vous devez vous authentifier"
            logout:
                path: /logout
                target: /
    providers:
        database:
            entity: { class: TrezLogicielTrezBundle:User, property: username }
        # mainly for first usage, using parameters.ini file
        in_memory:
            memory:
                users: %users%
    encoders:
        Trez\LogicielTrezBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: true
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: true
    acl:
        connection: default