Trez\LogicielTrezBundle\Entity\Budget:
    type: entity
    table: null
    repositoryClass: Trez\LogicielTrezBundle\Entity\BudgetRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
        verrouille:
            type: boolean
    manyToOne:
        exercice:
            targetEntity: Exercice
    oneToMany:
        categories:
            targetEntity: Categorie
            mappedBy: budget
    lifecycleCallbacks:
        preFlush: [ checkExerciceVerrouille ]
        preRemove: [ checkExerciceVerrouille ]
