Trez\LogicielTrezBundle\Entity\Config:
    type: entity
    table: null
    repositoryClass: Trez\LogicielTrezBundle\Entity\ConfigRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        cle:
            type: string
            length: 255
        valeur:
            type: string
            length: 255
    lifecycleCallbacks: {  }
