Trez\LogicielTrezBundle\Entity\Facture:
    type: entity
    table: null
    repositoryClass: Trez\LogicielTrezBundle\Entity\FactureRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        numero:
            type: integer
        objet:
            type: string
            length: '400'
        montant:
            type: decimal
            scale: 2
        date:
            type: date
        date_paiement:
            type: date
            nullable: true
        date_ecriture:
            type: date
            nullable: true
        commentaire:
            type: text
            nullable: true
        ref_paiement:
            type: string
            length: 255
            nullable: true
    oneToMany:
        tvas:
            targetEntity: Tva
            mappedBy: facture
            cascade: [ persist, remove ]
    manyToOne:
        ligne:
            targetEntity: Ligne
            inversedBy: factures
        tiers:
            targetEntity: Tiers
        methodePaiement:
            targetEntity: MethodePaiement
        typeFacture:
            targetEntity: TypeFacture
        declarationTva:
            targetEntity: DeclarationTva
    lifecycleCallbacks:
        preFlush: [ checkVerrouille ]
        preRemove: [ checkVerrouille ]
