Trez\LogicielTrezBundle\Entity\Ligne:
    type: entity
    table: null
    repositoryClass: Trez\LogicielTrezBundle\Entity\LigneRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
        commentaire:
            type: string
            length: '400'
            nullable: true
        cle:
            type: integer
        debit:
            type: decimal
        credit:
            type: decimal
    manyToOne:
        sousCategorie:
            targetEntity: SousCategorie
    lifecycleCallbacks: {  }
