Trez\LogicielTrezBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Trez\LogicielTrezBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        type:
            type: string
            length: 255
            nullable: true
    # will create a join table
    manyToMany:
        categories:
            targetEntity: Categorie
            inversedBy: users
    lifecycleCallbacks: {  }
