_welcome:
    pattern:  /
    defaults: { _controller: TrezLogicielTrezBundle:Default:index }

logout:
    pattern: /logout

login:
    pattern: /login
    defaults: { _controller: TrezLogicielTrezBundle:Security:login }

# legacy HTTP login support
login_http:
    pattern: /login_http
    defaults: { _controller: TrezLogicielTrezBundle:Default:index }

budget:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/budget.yml"
    prefix:   /budget

categorie:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie
    
classeTva:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/classeTva.yml"
    prefix:   /classeTva  
      
config:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/config.yml"
    prefix:   /configuration
    
exercice:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/exercice.yml"
    prefix:   /exercice
    
facture:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/facture.yml"
    prefix:   /facture
    
ligne:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/ligne.yml"
    prefix:   /ligne
    
methodePaiement:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/methodePaiement.yml"
    prefix:   /methodePaiement
    
sousCategorie:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/sousCategorie.yml"
    prefix:   /sous_categorie

templateFacture:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/templateFacture.yml"
    prefix:   /templateFacture

tiers:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/tiers.yml"
    prefix:   /tiers
    
typeFacture:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/typeFacture.yml"
    prefix:   /typeFacture
    
user:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/user.yml"
    prefix:   /user

# import FpOpenIdBundle routing
# login route is not used, login_check is ok, logout overriden
fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"