_welcome:
    pattern:  /
    defaults: { _controller: TrezLogicielTrezBundle:Default:index }

exercice:
    resource: "@TrezLogicielTrezBundle/Resources/config/routing/exercice.yml"
    prefix:   /exercice