parameters:
#    trez_logiciel_trez.example.class: Trez\LogicielTrezBundle\Example

services:
#    trez_logiciel_trez.example:
#        class: %trez_logiciel_trez.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.evaluate:
        class: Trez\LogicielTrezBundle\Twig\Extension\EvaluateExtension
        tags:
            - { name: twig.extension }
    trez.logiciel_trez.openid_user_manager:
        class: Trez\LogicielTrezBundle\Model\OpenIdUserManager
        arguments: [ @fp_openid.identity_manager, @doctrine.orm.entity_manager ]