parameters:
#    trez_logiciel_trez.example.class: Trez\LogicielTrezBundle\Example

services:
#    trez_logiciel_trez.example:
#        class: %trez_logiciel_trez.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
