budget_index:
    pattern:  /{exercice_id}
    defaults: { _controller: TrezLogicielTrezBundle:Budget:index }

budget_detail:
    pattern:  /detail/{id}/{view_factures}/{view_totals}
    defaults: { _controller: TrezLogicielTrezBundle:Budget:detail, view_factures: 0, view_totals: 0 }

budget_add:
    pattern: /add/{exercice_id}
    defaults: { _controller: TrezLogicielTrezBundle:Budget:add }

budget_edit:
    pattern: /edit/{exercice_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Budget:edit }

budget_delete:
    pattern: /delete/{exercice_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Budget:delete }

budget_duplicate:
    pattern: /duplicate/{exercice_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Budget:duplicate }