declaration_tva_index:
    pattern:  /
    defaults: { _controller: TrezLogicielTrezBundle:DeclarationTva:index }

declaration_tva_list_factures:
    pattern:  /list_factures/
    defaults: { _controller: TrezLogicielTrezBundle:DeclarationTva:listFactures }

declaration_tva_create:
    pattern:  /create/
    defaults: { _controller: TrezLogicielTrezBundle:DeclarationTva:create }

declaration_tva_generate_sheet:
    pattern:  /generate_sheet/{id}
    defaults: { _controller: TrezLogicielTrezBundle:DeclarationTva:generateSheet }