exercice_index:
    pattern:  /
    defaults: { _controller: TrezLogicielTrezBundle:Exercice:index }

exercice_add:
    pattern: /add
    defaults: { _controller: TrezLogicielTrezBundle:Exercice:add }

exercice_edit:
    pattern: /edit/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Exercice:edit }

exercice_delete:
    pattern: /delete/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Exercice:delete }

exercice_list_factures:
    pattern: /factures/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Exercice:listFactures }