facture_index:
    pattern:  /{ligne_id}
    defaults: { _controller: TrezLogicielTrezBundle:Facture:index }

facture_detail:
    pattern: /detail/{ligne_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Facture:detail }

facture_add:
    pattern: /add/{ligne_id}/{type_id}
    defaults: { _controller: TrezLogicielTrezBundle:Facture:add }

facture_edit:
    pattern: /edit/{ligne_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Facture:edit }

facture_print:
    pattern: /print/{ligne_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Facture:print }

facture_delete:
    pattern: /delete/{ligne_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Facture:delete }