ligne_index:
    pattern:  /{sous_categorie_id}
    defaults: { _controller: TrezLogicielTrezBundle:Ligne:index }
    
ligne_add:
    pattern: /add/{sous_categorie_id}
    defaults: { _controller: TrezLogicielTrezBundle:Ligne:add }

ligne_edit:
    pattern: /edit/{sous_categorie_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Ligne:edit }

ligne_delete:
    pattern: /delete/{sous_categorie_id}/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Ligne:delete }

ligne_adjust:
    pattern: /adjust/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Ligne:adjust }