tiers_index:
    pattern:  /
    defaults: { _controller: TrezLogicielTrezBundle:Tiers:index }
    
tiers_add:
    pattern: /add
    defaults: { _controller: TrezLogicielTrezBundle:Tiers:add }

tiers_edit:
    pattern: /edit/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Tiers:edit }

tiers_delete:
    pattern: /delete/{id}
    defaults: { _controller: TrezLogicielTrezBundle:Tiers:delete }