typeFacture_index:
    pattern:  /
    defaults: { _controller: TrezLogicielTrezBundle:TypeFacture:index }
    
typeFacture_add:
    pattern: /add
    defaults: { _controller: TrezLogicielTrezBundle:TypeFacture:add }

typeFacture_edit:
    pattern: /edit/{id}
    defaults: { _controller: TrezLogicielTrezBundle:TypeFacture:edit }

typeFacture_delete:
    pattern: /delete/{id}
    defaults: { _controller: TrezLogicielTrezBundle:TypeFacture:delete }
