user_index:
    pattern:  /
    defaults: { _controller: TrezLogicielTrezBundle:User:index }
  
user_add:
    pattern: /add
    defaults: { _controller: TrezLogicielTrezBundle:User:add }

user_edit:
    pattern: /edit/{id}
    defaults: { _controller: TrezLogicielTrezBundle:User:edit }

user_delete:
    pattern: /delete/{id}
    defaults: { _controller: TrezLogicielTrezBundle:User:delete }